# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_auto_20190901_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
