# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0006_auto_20190901_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='instaapp.Profile'),
        ),
    ]
