# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0021_auto_20190901_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
