# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0022_auto_20190902_0753'),
    ]

    operations = [
    ]
