# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0023_auto_20190902_0818'),
    ]

    operations = [
    ]
