# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0027_auto_20190915_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood_image',
            field=models.ImageField(blank=True, upload_to='hood/'),
        ),
    ]
